(add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
(setq js2-allow-keywords-as-property-names nil)
(setq js2-mode-show-strict-warnings nil)
(setq js2-basic-offset 4)
(setq js2-bounce-indent-p nil)
(setq js2-dynamic-idle-timer-adjust 10000)
(setq js2-highlight-external-variables nil)
(setq js2-idle-timer-delay 1)
(setq js2-mode-show-parse-errors t)
(setq js2-pretty-multiline-declarations t)
(setq js2-highlight-level 3)

(require 'js2-refactor)
(js2r-add-keybindings-with-prefix "C-c C-m")

;; (require 'flycheck)
;; (add-hook 'js2-mode-hook
;;           (lambda () (flycheck-mode t)))

(defun prettify-js-symbols ()
  (push '("lambda" . ?λ) prettify-symbols-alist)
  (push '("function" . ?ƒ) prettify-symbols-alist)
  (push '("return" . ?⟼) prettify-symbols-alist)
  (push '("<=" . ?≤) prettify-symbols-alist)
  (push '(">=" . ?≥) prettify-symbols-alist)
  (push '("!==" . ?≠) prettify-symbols-alist)
  (prettify-symbols-mode)
  (electric-pair-mode))

(add-hook 'js2-mode-hook 'prettify-js-symbols)
