(require 'tex)
(add-hook 'TeX-mode-hook (lambda ()
                           (local-set-key (kbd "C-c h") 'TeX-fold-dwim)
                           (local-set-key (kbd "C-f") 'LaTeX-fill-region)
                           (LaTeX-math-mode)
                           ;; (setq TeX-engine 'xetex)
                           (turn-on-reftex)))
(setq TeX-auto-save t)
(setq TeX-parse-self t)
(setq-default TeX-master nil)
(setq reftex-plug-into-AUCTeX t)
(TeX-global-PDF-mode t)
(setq LaTeX-indent-level 4)
(setq LaTeX-item-indent 0)
